FROM node:19-alpine as base
RUN mkdir /app
WORKDIR /app

# Build cache
FROM base as build
ADD package.json package-lock.json ./
RUN npm install

FROM build

ADD . .

# Add permission to .next folder
RUN mkdir /app/.next
RUN chmod ugo+rwx /app/.next

# Run application not as root
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

CMD ["npm", "run", "dev"]